name: Run tests

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  test-gtauthclient:
    uses: ./.github/workflows/operation-test-with-jupyter.yml
    with:
      notebook: tests.ipynb
      image: python:3.10
      port: "8091"
      clone-repo: true
